# Generated by Django 4.2.7 on 2023-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0002_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='User deleted', max_length=20)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
