# Generated by Django 4.2.7 on 2023-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(default='./static/img/none-logo.png', upload_to=''),
        ),
    ]
