# Generated by Django 4.2.7 on 2023-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0006_company_education_alter_user_img_vacancy_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
