# Generated by Django 4.2.7 on 2023-11-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0010_remove_vacancy_place_of_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
