# Generated by Django 4.2.7 on 2023-11-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0012_vacancy_employment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employment',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='employment',
            new_name='experience',
        ),
    ]
