# Generated by Django 4.2.7 on 2023-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0013_rename_employment_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(choices=[('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('One-time job', 'One-time job'), ('Internship', 'Internship')], default=None, max_length=255, null=True),
        ),
    ]
