# Generated by Django 4.2.7 on 2023-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0014_vacancy_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('Not required', 'Not required'), ('Higher', 'Higher'), ('Vocational', 'Vocational'), ('Specialized secondary', 'Specialized secondary')], default=None, max_length=255, null=True),
        ),
    ]
