# Generated by Django 4.2.7 on 2023-11-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0018_remove_vacancy_city_company_country_company_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='experience',
            field=models.CharField(choices=[('-', '-'), ('Without experience', 'Without experience'), ('Less than 1 years', 'Less than 1 years'), ('From 1 yo 3 years', 'From 1 yo 3 years'), ('More that 3 years', 'More that 3 years')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('-', '-'), ('Higher', 'Higher'), ('Vocational', 'Vocational'), ('Specialized secondary', 'Specialized secondary')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(choices=[('-', '-'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('One-time job', 'One-time job'), ('Internship', 'Internship')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('-', '-'), ('Without experience', 'Without experience'), ('Less than 1 years', 'Less than 1 years'), ('From 1 yo 3 years', 'From 1 yo 3 years'), ('More that 3 years', 'More that 3 years')], default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echoApp.user')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echoApp.vacancy')),
            ],
        ),
    ]
