# Generated by Django 4.2.7 on 2023-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0019_alter_summary_experience_alter_vacancy_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
