# Generated by Django 4.2.7 on 2023-11-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0021_rename_celery_vacancy_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='district',
        ),
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
    ]
