# Generated by Django 4.2.7 on 2023-11-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0023_alter_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echoApp.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echoApp.district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='echoApp.region'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echoApp.country'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN'), ('RUB', 'RUB')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echoApp.district'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echoApp.region'),
        ),
    ]
