# Generated by Django 4.2.7 on 2023-11-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoApp', '0025_summary_currency_summary_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='currency',
        ),
    ]
